### ISSUE TITLE
New elements in Kvantum 0.10.6

### ISSUE THREAD

**Issue by tsujan** [manjaro/kvantum-manjaro#2]
With Kvantum 0.10.6, checkboxes inside selected menu-items can be different and it's possible to have "tickless" slider handles. These changes are backward compatible. Is it OK if I add them to these themes and, probably, do some other cleanups as PRs -- without changing anything else? After all, I'm a Manjaro user.

**Comment by oberon2007** [comment]
Hi @tsujan and thank you! You are more than welcome to do that.
Originally what we did was simply adjust the color values of the original - so this is basically what we'd like to re-establish :smiley:
